global:
  scrape_interval: 15s # How often to check for data

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'docker-containers'
    static_configs:
      - targets: ['cadvisor:8080'] # We will name our container 'cadvisor'